# Generated by Django 2.2.7 on 2019-12-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=150)),
            ],
        ),
    ]
