# Generated by Django 2.2.7 on 2020-01-27 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('typ', models.CharField(max_length=20)),
                ('manager', models.CharField(max_length=15)),
                ('frontend', models.CharField(max_length=10)),
                ('backend', models.CharField(max_length=10)),
                ('client', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('u_email', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('mobile_no', models.IntegerField(null=True)),
                ('password', models.CharField(max_length=20)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('typ', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('start_date', models.CharField(max_length=20)),
                ('due_date', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='Bugz.User')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bugz.Project')),
            ],
        ),
    ]
