# Generated by Django 2.2.7 on 2020-01-02 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bugz', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='u_email',
        ),
    ]
