# Generated by Django 2.2.7 on 2020-01-07 03:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bugz', '0003_auto_20200102_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('typ', models.CharField(max_length=20)),
                ('manager', models.CharField(max_length=15)),
                ('frontend', models.CharField(max_length=10)),
                ('backend', models.CharField(max_length=10)),
                ('client', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='query',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('typ', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('start_date', models.CharField(max_length=20)),
                ('due_date', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='Bugz.User')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bugz.Project')),
            ],
        ),
    ]
