# Generated by Django 2.2.7 on 2020-01-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bugz', '0006_auto_20200115_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.IntegerField(),
        ),
    ]
