# Generated by Django 2.2.7 on 2020-01-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bugz', '0007_auto_20200116_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.IntegerField(null=True),
        ),
    ]
